version: '3.9'

services:
  db:
    image: mongo:latest
    restart: always
    #environment:
    #  - MONGO_INITDB_DATABASE=rozetka
    #  - MONGO_INITDB_ROOT_USERNAME=AdminMongo
    #  - MONGO_INITDB_ROOT_PASSWORD=Rozetka
    #networks:
    #  - mongodb
    ports:
      - 27018:27017
    volumes:
      - ./data_volume:/data/db
      
  scrapy_rozetka:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    links:
      - db
    environment:
      DB_NAME: rozetka
      DB_USERNAME: rozetka
      DB_PASSWORD: rozetka
      DB_HOST: db
      DB_PORT: 27018

volumes:
  data_volume:
